### ISSUE TITLE
Fatal error: Call to undefined function lcfirst() 

### ISSUE THREAD

**Issue by llermaly** [khipu/opencart-khipu#1]
Al seguir los pasos y tratar de efectuar un pago me tira este error luego de seleccionar khipu simplificada o transferencia electronica normal :+1: 

Notice: Trying to get property of non-object in \catalog\controller\payment\khipu_commons.php on line 40Warning: Invalid argument supplied for foreach() in \catalog\controller\payment\khipu_commons.php on line 40

Error anterior :

> Fatal error: Call to undefined function lcfirst() in (...)/opencart/catalog/controller/payment/lib-khipu/src/Khipu.php on line 116
> Solucion : Reemplazar la funcion debido a incompatibilidad con PHP

Estoy usando la Versión 1.5.6.4 de opencart y con template no default. Seguiré probando y de encontrar algo lo dejo por acá.

Gracias

**Comment by Vick-Alrc** [comment]
Hola como estan, a mi me pasa exactamente lo mismo que a llermaly pero yo estoy usando la version 2.0.0.0 de opencart.

¿han podido hayar el problema?

Gracias.

**Comment by almejo** [comment]
Hola!

Suponemos que el problema se produce por que están usando una versión de php más vieja que la que necesita el plugin. El plugin necesita PHP 5.3 o superior. Podrían confirmar cual es la versión de php que tienes en tu servidor? Durante el día subire una versión del archivo corregida para que la reemplazes en el servidor. Después actualizaremos oficialmente el plugin

**Comment by Vick-Alrc** [comment]
Yo estoy utilizando la versión 5.3.3 de PHP
Y alparecer lei mal el error de llermaly (es otro error) mi error es el siguiente:

Notice: Trying to get property of non-object in (..)/opencart/catalog/controller/payment/khipu_commons.php on line 38Warning: Invalid argument supplied for foreach() in (..)/opencart/catalog/controller/payment/khipu_commons.php on line 38

**Comment by almejo** [comment]
Hola

Estamos investigando el problema. Me puedes indicar si te sucede con pago manual, simplificado o ambos? 

También necesitaremos tu id de cuenta de cobro para buscar más información

**Comment by Vick-Alrc** [comment]
Me sucede de las 2 formas.

Mi ID es: 28849

**Comment by llermaly** [comment]
Finalmente era un problema del hosting (hostgator) tenian que deshabilitar la regla mod_security de php . Lo resolvi mediante chat y tomó un par de segundos. un saludo

**Comment by almejo** [comment]
Ok. voy a cerrar el ticket, pero seguiré revisando para ver cual es el problema con mod_security

suerte
