### ISSUE TITLE
rying to get property of non-object in khipu_commons.php on line 38

### ISSUE THREAD

**Issue by renobizarrox** [khipu/opencart-khipu#6]
i have this issue using opencart 2.0.3.1

my server has installed php 5.4.16(zend server 6.1) and mysql 5.6.14 on windows server 2003 R2

i get this following error:

Notice: Trying to get property of non-object in C:\WEB\catalog\controller\payment\khipu_commons.php on line 38
Warning: Invalid argument supplied for foreach() in C:\WEB\catalog\controller\payment\khipu_commons.php on line 38

i did make a print_r($banks); and the array comes empty, looks like khipu is not retrieving banks lists

i need some help here please.

**Comment by edavism** [comment]
Do you have php curl installed? when the $banks array is empty thats usually the case

**Comment by renobizarrox** [comment]
yes, i do have it installed, in my phpinfo(); i see

cURL support: enabled
cURL Information: 7.25.0

**Comment by edavism** [comment]
You also need sha256 support (khipu.com certificate use it), since it a windows 2003 server it may be missing. See http://serverfault.com/questions/606805/enabling-sha2-certificate-support-on-windows-server-2003

**Comment by renobizarrox** [comment]
is there a way to validate if my windows server has sha256 support?

**Comment by edavism** [comment]
Create a php file with the following code, if it prints the html source of khipu.com then you have a working curl + sha256 compatible server otherwise you don't and need to upgrade it.

<?php 
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://khipu.com"); 
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 
$output = curl_exec($ch); 
echo $output;
curl_close($ch);  
?>

**Comment by renobizarrox** [comment]
well.. your function returns me nothing...

but i don't see where the problem is, take a look:

http://donaciones.l2america.cl/khipu.php

it is generating sha256 hashes and curl is installed...

**Comment by edavism** [comment]
Yup, your php has sha256, but you http client does not, thats why you can't get the bank list nor the home page of khipu.com.

You are using an expired server (http://www.microsoft.com/en-us/server-cloud/products/windows-server-2003) and need to patch it, 

Either https://support.microsoft.com/en-us/kb/938397 o https://support.microsoft.com/en-us/kb/968730 should be able to help you.

**Comment by renobizarrox** [comment]
damn... i installed both updates but still doesn't work... do you know if i have to made some config in apache server after installing this?
