### ISSUE TITLE
Modulo no funciona en opencart 2.3.0.x

### ISSUE THREAD

**Issue by mcueto** [khipu/opencart-khipu#8]
Buenas, tengo el siguiente problema(además de otros que ya solucioné y que haré pull request pronto):

Resulta que tengo un sitio web en local, con el modulo instalado, activado y configurado, pero:
- Al momento de querer hacer el pago y seleccionar el método de pago(ya sea transferencia o transferencia simplificada) no se abre ningún popup, frame ni nada que permita realizar el pago, por lo tanto no puedo efectuar la integración.
- Como no puedo pagar no puedo concluir una compra.

Saludos

**Comment by edavism** [comment]
Hemos liberado la version 3.0.0 del plugin, compatible con opencart 3

**Comment by arcovirtual** [comment]
tengo el mismo problema, descargo el plugin para opencart 2.0 de la misma web de khipu y no funciona con OC2.3 solo me a funcionado con opencart 2.1 tengo un marketplace y queria implementar un plan de negocios basado solo en khipu por su baja comision pero no lo logre :( entonces no habra soporte para 2.3 de OC?

**Comment by T0malak** [comment]
Hola,

  Estoy copiando a nuestra área de soporte: soporte@khipu.com

Saludos,

  Enrique.


---------- Forwarded message ---------

**Comment by arcovirtual** [comment]
el error fue humano, agregue un espacio en blanco al copiar el código directo por esto no funcionaba. SOLUCIONADO comprobado en dos versiones 2.1 y 2.3 funciona correctamente. todo ok quizas sea necesario verificar el codigo fuente del sitio web donde copiamos las key para que al seleccionar exista un copy automatico asi no nos equivoquemos.- saludos

**Comment by Nyrk0** [comment]
Mismo problema, extensión Khipu OC2 funciona en OC2 pero no funciona en OC2.3 porque tiene nueva estructura de archivos (ver ejemplos OC2 y OC2.3 al final)

**Quien tenga Khipu funcionando en OC2.3 por favor coloquen los enlaces de descarga de la extensión adecuada en la página de Khipu.**

Ejemplo OC2 
<?php
class ControllerPaymentKhipu extends Controller {
	private $error = array();
	public function index() {
		$this->load->language('payment/khipu');
...

Ejemplo OC2.3
class ControllerExtensionPaymentBankTransfer extends Controller {
	private $error = array();
	public function index() {
		$this->load->language('extension/payment/bank_transfer');
...

**Comment by arcovirtual** [comment]
ok por si no quedo claro el erro esta en la pagina de khipu ya que el codigo agrega un espacio en blanco al final al tratar de copiarlo, esto se soluciona facil verificando el codigo que pegas en tu OC.

**Comment by arcovirtual** [comment]
mod khipu que me funciona en oc2.3 [https://www.mediafire.com/file/xhmdu3ets5egfsr/khipu.ocmod.zip/file](https://www.mediafire.com/file/xhmdu3ets5egfsr/khipu.ocmod.zip/file) estara disponible por 14 dias porque no tengo cuenta en mediafire saludos

**Comment by Nyrk0** [comment]
Hola,


Debes tener alguna extensión en tu OC2.3 para compatibilidad con extensiones viejas del OC2.0 porque el mod khipu que me enviaste es idéntico al que se baja de khipu.com con la estructura antigua y no funciona.


¿Cual extensión de compatibilidad tienes instalada en tu OC?


Saludos,

**Comment by arcovirtual** [comment]
ya intentaste revisar la clave de khipu? ejemplo el error es asi: [321321654613erereer3132132 ]<<< espacio en blanco al final, la solucion es [321321654613erereer3132132]<<<quitar el espacio en blanco al final en cada caso, ya no usamos khipu pero ese fue el error que teniamos en aquella oportunidad, las estructuras estan correctas en el mod de khipu, si tienes acceso al informe de errores de opencart pegalo aca para ver cual error te muestra si lo hace, quizas tengas alguna interaccion con algun mod de pago o con alguna interaccion en un mod de checkout, o carro de compras modificado por algun a extension o tambien estar usando un compresor de codigo ocmod, en general esos errores conozco de trabajos anteriores en varios paises sobre sistemas de pago, tambien importante maneter limpio el cache de modification y actualizar modification para que los cambios se realicen y si usas vqmod borrar el cache vqmod. no tenemos fix de oc2.3 para versiones anteriores. PD: khipu puede utilizarse desde muchos otros mod y plataformas (pasarelas de pago que contienen todos los medios de pago como payku)

**Comment by Nyrk0** [comment]
Hey muchas gracias, ya sabía eso del espacio porque fui usuario Khipu en OC 1.5 hace años antes de subir al OC 2.3


Las extensiones OC 2.0 NO SON COMPATIBLES CON OC 2.3 porque LAS ESTRUCTURAS CAMBIAN 
https://github.com/opencart/opencart/issues/4645




Saludos y gracias.
